spring.application.name=sprint1

spring.datasource.url=jdbc:postgresql://sprint2-postgres.c7y2kowyu6ih.ap-northeast-1.rds.amazonaws.com:5432/sprint2db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver